### PR TITLE
Delete repeating removals

### PR DESCRIPTION
**Pull request by hyunchel**
If I'm not mistaken, `brew prune` cleans those man-page if node/npm are removed.
A single shift in the order can save few lines of codes if you don't mind separating `brew` commands.

### CODE REVIEW

**Comment by DomT4** [comment]
Thank you for the PR!

I've been keeping both around as the script was initially designed for people who had installed Node using the upstream binary package, and then switched over to Homebrew and tried to use our package & hit build/link failure. In that situation `brew prune` didn't touch the `npm` manpages because they didn't "belong" to `brew`.

The next use case that came up was slightly different in that prior to https://github.com/Homebrew/homebrew/commit/f7ffaf6c8f563b264fe4abba5671d56a220e654d we used to install `npm` in `libexec` and then use `npm` to do `make uninstall` and `make install` in `HOMEBREW_PREFIX`. This also ended up with `brew` not knowing it owned the `npm` installation or the consequent manpages.

Use case number 2 is less of an issue since that commit, and on top of that we have extra logic in the `node` formula now to handle manpage linking. Use case 1 is still an issue if people are using `sudo` with `npm` in that scenario.

I'd like to keep the script with roughly the same mechanism as it uses now, but I've been meaning to make it more intelligent (i.e. not running the `brew` commands if no such command exists, not spending time trying to remove manpages if they're no longer present after `brew prune`, etc) so if you wanted to save me having to do that rewrite I'd be happy enough to accept it.

**Comment by hyunchel** [comment]
I apologize on the delayed response.
I am not proficient with bash script myself to fulfill your request in a short period of time.
When I get a chance, however, I will try to work on it.
It seems like this is not something you'd need ASAP, so I will take time to finish up this PR.
In the meantime, feel free to take the PR yourself whenever you find the need.
Thank you for the nice feedback :)

**Comment by DomT4** [comment]
Fixed via https://github.com/DomT4/scripts/commit/4e898c633aa309e3fd75e6bc62b559bb49e82700, a mere 2+ years later. Thank you for filing this PR at the time.

**Comment by hyunchel** [comment]
wow 2 years! time flies. thanks for the fix 👍

**Pull request closed without merging**
